### ISSUE TITLE
Can't connect to Google (besides start up pop up) 

### ISSUE THREAD

**Issue by jellewie** [kmisiunas/sweeper-craft#12]
Can't use connect to Google button in menu when not loged in

 (I did not have wifi turned on so I fixed that and openen the app again. Searched the options for this feature but could not get it to work. Restart ing the app did do the job fine).

**Comment by kmisiunas** [comment]
Mostly works now.

I will review this mechanism in next release. I think there might be some uncaught cases when there is internet but the server is blocked, etc.
