### ISSUE TITLE
Achievements not saved

### ISSUE THREAD

**Issue by jellewie** [kmisiunas/sweeper-craft#15]
Fist map I played I got achievements (huzay \0/ ) but when reloading (leave an continue or resize) the game gives them all again. Not a mager problem but I would inplent it so you can only get the screen one time.
On second through I can not stop them from coming. It seems to never save that I already have them. And it keeps display goed them over and over again

**Comment by kmisiunas** [comment]
This comes because we are saving java object. internal representation changed between versions because resource id's are different. Must store them as a database.

**Comment by kmisiunas** [comment]
Resolved now. Only storing the unique google id and progress.
