### ISSUE TITLE
Crashed app won't start

### ISSUE THREAD

**Issue by kmisiunas** [kmisiunas/sweeper-craft#3]
By JelleWho:

On this version after any error the game is unplayable. The game crashes on boot. Or says it's not installed "app is niet geïnstalleerd" like the attachment 20160728-091520 Only known way too fix this is to uninstall and reinstall the app (or remove all data of the app) Stopping the app and reboot the device don't work.

**Comment by jellewie** [comment]
Fixed -  found out that app didn't start while in landscape.

**Comment by kmisiunas** [comment]
I think this was caused by a special landscape layout. This 'feature' is deleted now
